project:
  type: website

website:
  title: "Elements of a Home Run"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer:
    center: "Elements of a Home Run | MLB Statcast 2025 Data Analysis"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



